# Using Files

In [4]:
# Read all file content

filename = "data/cairns-sst-2015.csv"

f = open(filename)
text = f.read()
f.close()

print(text)

Date and Time,Temperature (C)               
24/02/2015 11:30,28.962
24/02/2015 12:00,28.971
24/02/2015 12:30,29.051
24/02/2015 13:00,29.269
24/02/2015 13:30,29.53
24/02/2015 14:00,29.528
24/02/2015 14:30,29.619
24/02/2015 15:00,29.698
24/02/2015 15:30,29.853
24/02/2015 16:00,29.946
24/02/2015 16:30,30.346
24/02/2015 17:00,30.329
24/02/2015 17:30,30.149
24/02/2015 18:00,30.016
24/02/2015 18:30,30.133
24/02/2015 19:00,29.985
24/02/2015 19:30,30.02
24/02/2015 20:00,29.97
24/02/2015 20:30,29.721
24/02/2015 21:00,30.059
24/02/2015 21:30,30.016
24/02/2015 22:00,29.806
24/02/2015 22:30,29.603
24/02/2015 23:00,29.449
24/02/2015 23:30,29.176
25/02/2015 0:00,29.13
25/02/2015 0:30,29.059
25/02/2015 1:00,29.038
25/02/2015 1:30,29.02
25/02/2015 2:00,28.98
25/02/2015 2:30,28.967
25/02/2015 3:00,28.946
25/02/2015 3:30,28.91
25/02/2015 4:00,28.939
25/02/2015 4:30,28.947
25/02/2015 5:00,28.937
25/02/2015 5:30,28.91
25/02/2015 6:00,28.905
25/02/2015 6:30,28.875
25/02/2015 7:00,28.916
25/02/2015 7:30,28

In [5]:
with open(filename) as f:
    text = f.read()
print(text)

Date and Time,Temperature (C)               
24/02/2015 11:30,28.962
24/02/2015 12:00,28.971
24/02/2015 12:30,29.051
24/02/2015 13:00,29.269
24/02/2015 13:30,29.53
24/02/2015 14:00,29.528
24/02/2015 14:30,29.619
24/02/2015 15:00,29.698
24/02/2015 15:30,29.853
24/02/2015 16:00,29.946
24/02/2015 16:30,30.346
24/02/2015 17:00,30.329
24/02/2015 17:30,30.149
24/02/2015 18:00,30.016
24/02/2015 18:30,30.133
24/02/2015 19:00,29.985
24/02/2015 19:30,30.02
24/02/2015 20:00,29.97
24/02/2015 20:30,29.721
24/02/2015 21:00,30.059
24/02/2015 21:30,30.016
24/02/2015 22:00,29.806
24/02/2015 22:30,29.603
24/02/2015 23:00,29.449
24/02/2015 23:30,29.176
25/02/2015 0:00,29.13
25/02/2015 0:30,29.059
25/02/2015 1:00,29.038
25/02/2015 1:30,29.02
25/02/2015 2:00,28.98
25/02/2015 2:30,28.967
25/02/2015 3:00,28.946
25/02/2015 3:30,28.91
25/02/2015 4:00,28.939
25/02/2015 4:30,28.947
25/02/2015 5:00,28.937
25/02/2015 5:30,28.91
25/02/2015 6:00,28.905
25/02/2015 6:30,28.875
25/02/2015 7:00,28.916
25/02/2015 7:30,28

In [7]:
# Looping through file content
with open(filename) as f:
    for line in f:
        print(line.strip())


Date and Time,Temperature (C)
24/02/2015 11:30,28.962
24/02/2015 12:00,28.971
24/02/2015 12:30,29.051
24/02/2015 13:00,29.269
24/02/2015 13:30,29.53
24/02/2015 14:00,29.528
24/02/2015 14:30,29.619
24/02/2015 15:00,29.698
24/02/2015 15:30,29.853
24/02/2015 16:00,29.946
24/02/2015 16:30,30.346
24/02/2015 17:00,30.329
24/02/2015 17:30,30.149
24/02/2015 18:00,30.016
24/02/2015 18:30,30.133
24/02/2015 19:00,29.985
24/02/2015 19:30,30.02
24/02/2015 20:00,29.97
24/02/2015 20:30,29.721
24/02/2015 21:00,30.059
24/02/2015 21:30,30.016
24/02/2015 22:00,29.806
24/02/2015 22:30,29.603
24/02/2015 23:00,29.449
24/02/2015 23:30,29.176
25/02/2015 0:00,29.13
25/02/2015 0:30,29.059
25/02/2015 1:00,29.038
25/02/2015 1:30,29.02
25/02/2015 2:00,28.98
25/02/2015 2:30,28.967
25/02/2015 3:00,28.946
25/02/2015 3:30,28.91
25/02/2015 4:00,28.939
25/02/2015 4:30,28.947
25/02/2015 5:00,28.937
25/02/2015 5:30,28.91
25/02/2015 6:00,28.905
25/02/2015 6:30,28.875
25/02/2015 7:00,28.916
25/02/2015 7:30,28.913
25/02/2015

# CSV Library

In [9]:
import csv
filename = "data/cairns-sst-2015.csv"

with open(filename) as csvfile:
    csv_reader = csv.reader(csvfile)
    header = next(csv_reader)
    for row in csv_reader:
        print(row)


['24/02/2015 11:30', '28.962']
['24/02/2015 12:00', '28.971']
['24/02/2015 12:30', '29.051']
['24/02/2015 13:00', '29.269']
['24/02/2015 13:30', '29.53']
['24/02/2015 14:00', '29.528']
['24/02/2015 14:30', '29.619']
['24/02/2015 15:00', '29.698']
['24/02/2015 15:30', '29.853']
['24/02/2015 16:00', '29.946']
['24/02/2015 16:30', '30.346']
['24/02/2015 17:00', '30.329']
['24/02/2015 17:30', '30.149']
['24/02/2015 18:00', '30.016']
['24/02/2015 18:30', '30.133']
['24/02/2015 19:00', '29.985']
['24/02/2015 19:30', '30.02']
['24/02/2015 20:00', '29.97']
['24/02/2015 20:30', '29.721']
['24/02/2015 21:00', '30.059']
['24/02/2015 21:30', '30.016']
['24/02/2015 22:00', '29.806']
['24/02/2015 22:30', '29.603']
['24/02/2015 23:00', '29.449']
['24/02/2015 23:30', '29.176']
['25/02/2015 0:00', '29.13']
['25/02/2015 0:30', '29.059']
['25/02/2015 1:00', '29.038']
['25/02/2015 1:30', '29.02']
['25/02/2015 2:00', '28.98']
['25/02/2015 2:30', '28.967']
['25/02/2015 3:00', '28.946']
['25/02/2015 3:30', '

In [11]:
import csv, statistics
filename = "data/cairns-sst-2015.csv"

years = {2015: [], 2016: []}

with open(filename) as csvfile:
    # default is comma delimiter (but you can set one yourself)
    csv_reader = csv.reader(csvfile)
    header = next(csv_reader)
    for date_time, temp in csv_reader:
        if "2015" in date_time:
            years[2015].append(float(temp))
        elif "2016" in date_time:
            years[2016].append(float(temp))

for year, temps in years.items():
    print(year, round(statistics.mean(temps), 2)) 

2015 26.07
2016 29.53


In [12]:
import csv
with open('ave_surface_temp.csv', 'w') as csvfile:
    csvwriter = csv.writer(csvfile)
    csvwriter.writerow(["Year", "Average surface temp (C)"])
    for year, temps in years.items():
        csvwriter.writerow([year, round(statistics.mean(temps), 2)])

# Numpy

In [15]:
import numpy as np
test = np.array([1,2,3,4,5])
print(test)

[1 2 3 4 5]


In [18]:
from numpy import genfromtxt
my_data = genfromtxt('data/UQ Tesla Battery - 2021 (5-min resolution).csv', delimiter=',', skip_header=1)
print(my_data)

[[         nan          nan 2.050291e+03 ... 1.730000e+00 1.730000e+00
  8.700000e-01]
 [         nan          nan 2.050291e+03 ... 1.730000e+00 1.490000e+00
  8.700000e-01]
 [         nan          nan 2.050291e+03 ... 1.730000e+00 1.600000e+00
  8.700000e-01]
 ...
 [         nan          nan 2.108008e+03 ... 2.950000e+00 2.290000e+00
  8.000000e-01]
 [         nan          nan 2.108013e+03 ... 2.000000e+00 2.010000e+00
  8.000000e-01]
 [         nan          nan          nan ... 1.600000e+00 1.730000e+00
  8.000000e-01]]


## Basic array features - shape, index, slice

In [22]:
# Check the shape
print(my_data.shape)

# Select a single column
print(my_data[:,3])

# Select multiple columns
print(my_data[:,3:7])


(38305, 24)
[559.582 559.582 559.582 ... 235.612 239.488     nan]
[[559.582 583.773     nan     nan]
 [559.582 583.773     nan     nan]
 [559.582 583.737     nan     nan]
 ...
 [235.612 178.345     nan     nan]
 [239.488 179.522     nan     nan]
 [    nan     nan     nan     nan]]


## Fast array maths for a whole column - no loops required!

In [24]:
# Nominal and Expected energy difference

# Create a new array from 2 other arrays
difference = my_data[:,3] - my_data[:,4]
print(difference)

[-24.191 -24.191 -24.155 ...  57.267  59.966     nan]


## Maths on arrays

In [26]:
import numpy as np
test = np.array([1,2,3,4,5])
test = np.array([1,2,3,4,5, np.nan])
test = np.append(test, np.nan)

print(test)
print(np.shape(test))
print(np.sum(test))
print(np.nansum(test))

[ 1.  2.  3.  4.  5. nan nan]
(7,)
nan
15.0


In [27]:
# Complete min, max, mean, median (or the NAN versions of them) on any array or slice

print(np.nanmax(my_data[:,3]))
print(np.nanmin(my_data[:,3]))
print(np.nanmean(my_data[:,3]))
print(np.nanmedian(my_data[:,3]))

2106.24
0.0
1020.5711191848283
974.8875


## Working with data and writing it to a file

In [29]:
# reading from CSV converts non numerical data to NAN automatically

my_data = genfromtxt('data/UQ Tesla Battery - 2021 (5-min resolution).csv', delimiter=',', skip_header=1)

# Real Energy Imported (kWh) Index
imported_index = 15
exported_index = 16

# energy that didn't make it back out (maybe it was used as part of the frequency monitoring of the grid)
loss = my_data[:,imported_index] - my_data[:,exported_index]
print(np.nansum(loss))

percent_loss =  1 - my_data[:,exported_index]/my_data[:,imported_index]
print(percent_loss)
print(np.nanmean(percent_loss))


4339547040.768001
[0.1468564  0.1468564  0.14685648 ... 0.14590784 0.14591155        nan]
0.14787473205669538


### Joining data

In [32]:
# Add another column of data
test2 = np.array([[1,2,3],
                 [5,6,7]])
print(test2)
col = np.array([4,8])
col = np.vstack(col)

print(col)

np.append(test2, col, axis=1)

[[1 2 3]
 [5 6 7]]
[[4]
 [8]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
percent_loss = np.vstack(percent_loss)

# print(percent_loss)

new_data = np.append(my_data[:,imported_index:exported_index + 1], percent_loss, axis=1)
print(new_data.shape)
np.savetxt("percent_loss.csv", new_data, delimiter=",")

(38305, 3)


# Pandas

In [38]:
import pandas as pd 
# to install it use pip install pandas

koala_data = pd.read_csv('data/koala_sightings_data.csv') 
print(koala_data.shape)
print(koala_data.info())

(649, 32)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   _id                      649 non-null    int64  
 1   SurveyArea               649 non-null    object 
 2   LGA                      649 non-null    object 
 3   BushlandOrUrban          649 non-null    object 
 4   Methodology              649 non-null    object 
 5   Date                     649 non-null    object 
 6   Time                     645 non-null    object 
 7   TransectID               649 non-null    float64
 8   Year                     649 non-null    int64  
 9   SurveyNumber             649 non-null    int64  
 10  SiteNumber               649 non-null    int64  
 11  SiteName                 649 non-null    object 
 12  Transect                 649 non-null    float64
 13  SightingNumber           649 non-null    int64  
 14  Distance_m      

In [41]:
print(koala_data["LGA"].describe())
print()
print(koala_data["HeightOfKoalaInTree_m"].describe())
print()
print(koala_data["HeightOfKoalaInTree_m"])

0      12.0
1      22.0
2       9.0
3       9.0
4       8.0
       ... 
644    17.0
645    22.0
646     0.0
647     8.0
648     NaN
Name: HeightOfKoalaInTree_m, Length: 649, dtype: float64


In [43]:
koala_data.columns
koala_data.LGA.unique()

array(['Logan City', 'Redland City', 'Brisbane City', 'Moreton Bay',
       'Ipswich', 'Logan', 'Gold Coast', 'Noosa'], dtype=object)

In [44]:
golden_koalas = koala_data.loc[koala_data["LGA"] == "Gold Coast"]
print(golden_koalas)


     _id  SurveyArea         LGA BushlandOrUrban     Methodology        Date  \
511  512  Gold Coast  Gold Coast        Bushland  Strip-transect  20/07/2012   
512  513  Gold Coast  Gold Coast        Bushland  Strip-transect   3/08/2012   
513  514  Gold Coast  Gold Coast        Bushland  Strip-transect   9/08/2012   
514  515  Gold Coast  Gold Coast        Bushland  Strip-transect  21/08/2012   
515  516  Gold Coast  Gold Coast        Bushland  Strip-transect  22/08/2012   
516  517  Gold Coast  Gold Coast        Bushland  Strip-transect  28/08/2012   
517  518  Gold Coast  Gold Coast        Bushland  Strip-transect   7/03/2013   
518  519  Gold Coast  Gold Coast        Bushland  Strip-transect  13/03/2013   
519  520  Gold Coast  Gold Coast        Bushland  Strip-transect  13/03/2013   
520  521  Gold Coast  Gold Coast        Bushland  Strip-transect  14/03/2013   
521  522  Gold Coast  Gold Coast        Bushland  Strip-transect  14/03/2013   
522  523  Gold Coast  Gold Coast        

In [45]:
golden_koalas["NumberOfAdults"].sum()

49

## Write to a file

In [46]:
golden_koalas.to_csv("golden_koalas.csv")